// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZJiYEtN7gHX-cZBiFXS_Gd6U7eEs2I7E',
    appId: '1:442283477331:web:2f01f96f65c38e705639a6',
    messagingSenderId: '442283477331',
    projectId: 'journal-trend-analyzer-3f87b',
    authDomain: 'journal-trend-analyzer-3f87b.firebaseapp.com',
    storageBucket: 'journal-trend-analyzer-3f87b.firebasestorage.app',
    measurementId: 'G-FXWDJBK1SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl9-x4nB2OFCd8lTLlBtqDW2DtiDlptaA',
    appId: '1:442283477331:android:6c29df5c0df0184b5639a6',
    messagingSenderId: '442283477331',
    projectId: 'journal-trend-analyzer-3f87b',
    storageBucket: 'journal-trend-analyzer-3f87b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2FnChaE0XiwJ9LTP6-tUIn3h4_jyJZhk',
    appId: '1:442283477331:ios:2a165f1354f398ec5639a6',
    messagingSenderId: '442283477331',
    projectId: 'journal-trend-analyzer-3f87b',
    storageBucket: 'journal-trend-analyzer-3f87b.firebasestorage.app',
    iosBundleId: 'com.prm.journalTrendAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2FnChaE0XiwJ9LTP6-tUIn3h4_jyJZhk',
    appId: '1:442283477331:ios:49437590f3ead03d5639a6',
    messagingSenderId: '442283477331',
    projectId: 'journal-trend-analyzer-3f87b',
    storageBucket: 'journal-trend-analyzer-3f87b.firebasestorage.app',
    iosBundleId: 'com.example.journalTrendAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZJiYEtN7gHX-cZBiFXS_Gd6U7eEs2I7E',
    appId: '1:442283477331:web:b9d1e9372754c50e5639a6',
    messagingSenderId: '442283477331',
    projectId: 'journal-trend-analyzer-3f87b',
    authDomain: 'journal-trend-analyzer-3f87b.firebaseapp.com',
    storageBucket: 'journal-trend-analyzer-3f87b.firebasestorage.app',
    measurementId: 'G-5236LDSM2H',
  );
}
