/**
 * Centralized UI strings for the admin dashboard.
 *
 * All user-facing copy lives here (English for now) so that adding i18n later is
 * a matter of swapping this object for a locale-keyed lookup rather than hunting
 * strings across components.
 */
export const strings = {
  app: {
    name: 'Journal Trend Analyzer',
    adminSuffix: 'Admin',
    tagline: 'Firebase administration console',
  },

  login: {
    title: 'Admin Console',
    subtitle: 'Sign in with your authorized Google account to manage the Journal Trend Analyzer backend.',
    googleButton: 'Sign in with Google',
    signingIn: 'Signing in…',
    poweredBy: 'Secured by Firebase Authentication',
    error: 'Sign-in failed. Please try again.',
  },

  accessDenied: {
    title: 'Access denied',
    message:
      'This Google account is not registered as an administrator. Ask a project owner to add your email to the "admins" collection, then sign in again.',
    signOut: 'Sign out',
  },

  auth: {
    checking: 'Verifying your access…',
    signOut: 'Sign out',
    signingOut: 'Signing out…',
    signOutError: 'Sign-out failed. Please try again.',
  },

  nav: {
    dashboard: 'Overview',
    users: 'User management',
    notifications: 'Notifications',
    config: 'Remote Config',
    reports: 'File manager',
    logs: 'Audit logs',
    sectionMain: 'General',
    sectionFirebase: 'Firebase services',
    drawerLabel: 'Navigation menu',
  },

  pages: {
    dashboard: {
      title: 'Overview',
      subtitle: 'System status and quick access to Firebase services',
    },
    users: {
      title: 'User management',
      subtitle: 'View and manage authenticated app users',
    },
    notifications: {
      title: 'Notifications',
      subtitle: 'Send push messages to app users via Cloud Messaging',
    },
    config: {
      title: 'Remote Config',
      subtitle: 'Tune runtime parameters without shipping an app update',
    },
    reports: {
      title: 'File manager',
      subtitle: 'Browse, upload and manage files in Cloud Storage',
    },
    logs: {
      title: 'Audit logs',
      subtitle: 'Every write/delete action performed from this console',
    },
  },

  placeholder: {
    badge: 'Coming soon',
    title: 'Coming in a later phase',
    message:
      'This section is part of the admin console roadmap and will be implemented in a later phase.',
  },

  states: {
    loading: 'Loading…',
    emptyTitle: 'Nothing here yet',
    errorTitle: 'Something went wrong',
    retry: 'Try again',
  },

  topbar: {
    roleLabel: 'Administrator',
  },

  common: {
    open: 'Open',
    copy: 'Copy',
    copied: 'Link copied',
    delete: 'Delete',
    cancel: 'Cancel',
    close: 'Close',
    retry: 'Try again',
    loadMore: 'Load more',
    search: 'Search',
    all: 'All',
    viewAll: 'View all',
    none: '—',
  },

  users: {
    searchPlaceholder: 'Search by name or email…',
    sortLabel: 'Sort by',
    sortLastLogin: 'Last login',
    sortCreated: 'Created date',
    countLabel: (n: number) => `${n} user${n === 1 ? '' : 's'} loaded`,
    emptyTitle: 'No users yet',
    emptyMessage: 'Once someone signs in to the mobile app, they will appear here.',
    noMatch: 'No users match your search.',
    errorMessage: 'Could not load users from Firestore.',
    col: {
      user: 'User',
      email: 'Email',
      created: 'Created',
      lastLogin: 'Last login',
      searches: 'Searches',
      exports: 'Exports',
    },
    detail: {
      title: 'User details',
      profile: 'Profile',
      activity: 'Activity',
      uid: 'UID',
      platform: 'Platform',
      lastActive: 'Last active',
      reportsTitle: 'Exported reports',
      noReports: 'This user has not exported any reports yet.',
      reportsError: 'Could not load this user’s reports.',
    },
  },

  reports: {
    totalSize: 'Total storage used',
    reportCount: (n: number) => `${n} report${n === 1 ? '' : 's'}`,
    filterTopic: 'Topic',
    filterRange: 'Time range',
    range7: 'Last 7 days',
    range30: 'Last 30 days',
    rangeAll: 'All time',
    allTopics: 'All topics',
    storageWarning:
      'Storage folder could not be read — file sizes and total usage are unavailable.',
    emptyTitle: 'No reports yet',
    emptyMessage: 'Exported PDF reports from the app will show up here.',
    noMatch: 'No reports match the selected filters.',
    errorMessage: 'Could not load reports from Firestore.',
    col: {
      fileName: 'File name',
      topic: 'Topic',
      exportedBy: 'Exported by',
      date: 'Date',
      size: 'Size',
      actions: 'Actions',
    },
    deleteTitle: 'Delete report?',
    deleteMessage: (fileName: string) =>
      `This permanently removes “${fileName}” from Cloud Storage and its Firestore record. This cannot be undone.`,
    deleting: 'Deleting…',
    deleteSuccess: 'Report deleted.',
    deleteError: 'Could not delete the report. Please try again.',
  },

  overview: {
    kpiUsers: 'Total users',
    kpiActive: 'Active (7 days)',
    kpiSearches: 'Total searches',
    kpiReports: 'Reports exported',
    chartTitle: 'Exports per day',
    chartSubtitle: 'Last 14 days',
    chartEmpty: 'No exports in the last 14 days.',
    recentUsers: 'Recent logins',
    recentReports: 'Recent reports',
    recentUsersEmpty: 'No users yet.',
    recentReportsEmpty: 'No reports yet.',
    errorMessage: 'Could not load dashboard metrics from Firestore.',
    monitoringTitle: 'Advanced monitoring',
    monitoringNote:
      'Crashlytics and Analytics have no public web API suitable for embedding here, so no data is simulated — open them directly in the Firebase Console.',
    crashlyticsCard: 'Crashlytics',
    crashlyticsDesc: 'Crash-free users, stack traces and non-fatals.',
    analyticsCard: 'Analytics DebugView',
    analyticsDesc: 'Live events stream from instrumented devices.',
    openConsole: 'Open in Firebase Console',
  },

  notify: {
    formTitle: 'Compose notification',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. New research trends available',
    bodyLabel: 'Message',
    bodyPlaceholder: 'Write the notification body…',
    targetLabel: 'Audience',
    targetAll: 'All users',
    targetPick: 'Choose users',
    targetToken: 'Manual token',
    tokenPlaceholder: 'Paste a device FCM token',
    pickerSearch: 'Search users…',
    pickerEmpty: 'No users to choose from.',
    selectedCount: (n: number) => `${n} selected`,
    previewTitle: 'Preview',
    previewApp: 'Journal Trend Analyzer',
    previewNow: 'now',
    sendButton: 'Send notification',
    sending: 'Sending…',
    confirmTitle: 'Send this notification?',
    confirmAll: 'This will be sent to all users who have the app installed.',
    confirmUids: (n: number) => `This will be sent to ${n} selected user(s).`,
    confirmToken: 'This will be sent to the single device token provided.',
    confirmSend: 'Send',
    sentToast: (ok: number) => `Sent · ${ok} delivered`,
    errorToast: 'Could not send the notification.',
    validation: 'Title and message are required.',
    noTarget: 'Select at least one recipient.',
    historyTitle: 'Send history',
    historyEmpty: 'No notifications sent yet.',
    historyError: 'Could not load the send history.',
    resend: 'Resend',
    col: {
      title: 'Title',
      audience: 'Audience',
      result: 'Result',
      sentBy: 'Sent by',
      when: 'When',
    },
    resultOk: (ok: number, fail: number) => `${ok} ok · ${fail} failed`,
  },

  config: {
    tableTitle: 'Parameters',
    addButton: 'Add parameter',
    reload: 'Reload',
    publishButton: 'Save & Publish',
    publishing: 'Publishing…',
    pendingCount: (n: number) => `${n} pending change${n === 1 ? '' : 's'}`,
    lastPublish: 'Last published',
    by: 'by',
    never: 'Never published',
    effectNote:
      'Changes take effect the next time the app fetches Remote Config (users can pull to refresh in Profile).',
    emptyTitle: 'No parameters',
    emptyMessage: 'Add your first Remote Config parameter to get started.',
    errorMessage: 'Could not load the Remote Config template.',
    loadError: 'Could not read Remote Config. Is the Remote Config API enabled?',
    col: {
      name: 'Name',
      type: 'Type',
      value: 'Value',
      description: 'Description',
      actions: '',
    },
    newTitle: 'New parameter',
    fieldName: 'Parameter name',
    fieldType: 'Type',
    fieldValue: 'Default value',
    fieldDescription: 'Description (optional)',
    typeNumber: 'Number',
    typeString: 'String',
    typeBoolean: 'Boolean',
    add: 'Add',
    duplicateName: 'A parameter with that name already exists.',
    invalidName: 'Use letters, numbers and underscores only.',
    markedDelete: 'Marked for deletion',
    confirmTitle: 'Publish Remote Config changes?',
    confirmIntro: 'Review the changes below. Publishing applies them all at once.',
    before: 'Before',
    after: 'After',
    added: 'Added',
    removed: 'Removed',
    changed: 'Changed',
    publishedToast: 'Remote Config published.',
    publishError: 'Publish failed.',
    noChanges: 'No changes to publish.',
  },

  usersAdmin: {
    reload: 'Reload',
    searchPlaceholder: 'Search by name or email…',
    countLabel: (n: number) => `${n} account${n === 1 ? '' : 's'}`,
    errorMessage: 'Could not load users. Are the functions deployed?',
    emptyTitle: 'No accounts',
    emptyMessage: 'Authentication has no users yet.',
    noMatch: 'No accounts match your search.',
    statusActive: 'Active',
    statusDisabled: 'Locked',
    badgeAdmin: 'Admin',
    badgeNoProfile: 'No profile',
    col: {
      user: 'User',
      status: 'Status',
      created: 'Created',
      lastSignIn: 'Last sign-in',
      actions: 'Actions',
    },
    lock: 'Lock',
    unlock: 'Unlock',
    delete: 'Delete',
    lockedToast: 'Account locked.',
    unlockedToast: 'Account unlocked.',
    actionError: 'The action failed. Please try again.',
    lockConfirmTitle: 'Lock this account?',
    lockConfirmBody: (email: string) =>
      `${email} will be blocked from signing in until you unlock them.`,
    unlockConfirmTitle: 'Unlock this account?',
    unlockConfirmBody: (email: string) => `${email} will be able to sign in again.`,
    deleteTitle: 'Delete user permanently',
    deleteWarning:
      'This deletes the Auth account, the Firestore profile, all of the user’s report documents, and their PDF files in Storage. This cannot be undone.',
    deleteTypeHint: (email: string) => `Type ${email} to confirm.`,
    deleteTypePlaceholder: 'Type the email to confirm',
    deletedToast: 'User deleted.',
    deleteError: 'Delete failed.',
    cannotSelf: 'You cannot delete your own account.',
    cannotAdmin: 'Admin accounts cannot be deleted here.',
    deleteSummary: (r: number, f: number) =>
      `Removed account, profile, ${r} report(s) and ${f} file(s).`,
  },

  files: {
    totalUsed: 'Total storage used',
    fileCount: (n: number) => `${n} file${n === 1 ? '' : 's'}`,
    reload: 'Reload',
    upload: 'Upload',
    newFolder: 'New folder',
    uploading: 'Uploading…',
    dropHint: 'Drag & drop files here, or click Upload',
    acceptHint: 'PDF, PNG or JPG · up to 10 MB each',
    rejectedType: 'Only PDF, PNG and JPG files are allowed.',
    rejectedSize: 'Files must be 10 MB or smaller.',
    uploadedToast: 'Upload complete.',
    uploadError: 'Upload failed.',
    errorMessage: 'Could not read this folder from Storage.',
    emptyTitle: 'This folder is empty',
    emptyMessage: 'Upload a file or create a folder to get started.',
    root: 'reports',
    col: {
      name: 'Name',
      size: 'Size',
      type: 'Type',
      modified: 'Modified',
      actions: 'Actions',
    },
    selectedCount: (n: number) => `${n} selected`,
    deleteSelected: 'Delete selected',
    open: 'Open',
    download: 'Download',
    copy: 'Copy link',
    rename: 'Rename',
    deletedToast: 'Deleted.',
    deleteError: 'Delete failed.',
    deleteOneTitle: 'Delete file?',
    deleteOneBody: (name: string) => `“${name}” will be permanently removed from Storage.`,
    deleteManyTitle: 'Delete selected files?',
    deleteManyBody: (n: number) => `${n} file(s) will be permanently removed from Storage.`,
    renameTitle: 'Rename file',
    renameLabel: 'New file name',
    renamedToast: 'File renamed.',
    renameError: 'Rename failed.',
    newFolderTitle: 'New folder',
    newFolderLabel: 'Folder name',
    folderCreatedToast: 'Folder created.',
    folderError: 'Could not create the folder.',
    create: 'Create',
    invalidFolder: 'Use letters, numbers, - and _ only.',
  },

  logs: {
    reload: 'Reload',
    filterAction: 'Action',
    allActions: 'All actions',
    countLabel: (n: number) => `${n} entr${n === 1 ? 'y' : 'ies'} loaded`,
    emptyTitle: 'No activity yet',
    emptyMessage: 'Admin write/delete actions will be recorded here.',
    noMatch: 'No entries match this filter.',
    errorMessage: 'Could not load audit logs.',
    col: {
      when: 'When',
      actor: 'Admin',
      action: 'Action',
      target: 'Target',
      result: 'Result',
    },
  },
} as const;

export type Strings = typeof strings;
